version: "3.9"
services:
  db:
    image: postgres:12
    volumes:
      - ./app_source/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app_source:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
